### ISSUE TITLE
App Crashes and Closes Upon New Display Folder Creation

### ISSUE THREAD

**Issue by MuddasarM** [TabularEditor/TabularEditor3#184] opened 2021-08-16 14:57 UTC
Build 3.0.7892.27410

Steps:

Selected 3 measures from existing Display Folder
Right-click and select Copy
Select existing Display Folder, Right-click and select Paste
While 3 new measures are still selected, Right-click and select Create New Display Folder

Then app crashes and closes.

**Comment by kevarnold972** [comment] 2021-08-16 15:38
I have a similar issue when creating a new table and/or a new data column. 
Build 3.0.7892.27410

I'm editing a model.bim file. I have tried adding the object when connected to a workspace and not connected. The crash still occurred. 

If I added the table and saved the file before the crash I could edit it just fine. I was able to create the data columns by using copy/paste and then change properties. I noticed that the name in the TOM Explorer would be empty, but show in the property box when the tool would crash.

**Comment by ManuelMendozaLevo** [comment] 2021-08-17 02:16
Same happens when trying to create a new calculated column.

**Comment by otykier** [comment] 2021-08-17 06:17
I'm sorry, but I'm not able to reproduce any of the issues described in this thread with 3.0.7892.27410.

It would be very helpful if someone could provide a minimal .bim file that reproduces the issue, along with a gif recording that shows how to trigger the crash.

**Comment by ManuelMendozaLevo** [comment] 2021-08-18 14:56
Hi @otykier it seems to be happening randomly.
It happened to me twice with 2 different files (power bi) but can't seem to replicate the issue right now.
If it happens again, I'll make sure to record it because when it happens it basically makes the tool unusable.

**Comment by MuddasarM** [comment] 2021-09-04 22:54
@otykier Example was shared via email on 17/08/2021.

**Comment by otykier** [comment] 2021-09-05 04:54
Thanks @MuddasarM. I think I managed to find the root cause. A fix will be published later today.

**Comment by otykier** [comment] 2021-09-05 23:12
I believe this is now fixed in [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0). Feel free to reopen if you still encounter this issue.

**Closed by otykier** 2021-09-05 23:12 UTC
Labels: bug
