### ISSUE TITLE
Save Failed

### ISSUE THREAD

**Issue by JohnnyWinterWaterstons** [TabularEditor/TabularEditor3#322] opened 2021-12-15 09:58 UTC
I have a Tabular Model solution which I have source controlled using the 'Save to Folder' option. I have associated this with aWorkspace Database in the Power BI Service. When I go to do development work on the model, I open the database.json file and this reconnects me to the workspace via the .tmuo file

If I make changes to the model and then use the save option (ctrl + s) - "Save changes back to the currently loaded folder AND synchronizes the workspace" I get the following error:

- Cannot create "....\database.json" because a file or directory with the same name already exist

![error msg](https://user-images.githubusercontent.com/89249236/146163757-4da7f83d-0183-40da-8d62-42341a514ba1.png)
s

**Comment by otykier** [comment] 2021-12-15 10:21
Thanks for reporting. Does this also happen when you use the **File > Save to Folder...** option? What if you try to save to a different location?

**Comment by JohnnyWinterWaterstons** [comment] 2021-12-15 10:55
‘Save to Folder’ does work, so that the change is saved to my repo, but the change doesn’t then sync to the workspace for testing/debugging etc..

Thanks
Johnny


Johnny Winter
Senior Data & Analytics Consultant

T: +44 345 094 0945<tel:+443450940945>
M: 07842313292<tel:07842313292>
waterstons.com<https://www.waterstons.com/?utm_source=signature&utm_medium=email&utm_campaign=homepage>
www.waterstons.com/Johnny-Winter

[Waterstons]<waterstons.com>

 ***@***.*** <https://www.linkedin.com/company/waterstons>  ***@***.*** <https://twitter.com/waterstonsltd>  ***@***.*** <https://instagram.com/waterstonsltd>

**Comment by otykier** [comment] 2021-12-16 15:33
Hi @JohnnyWinterWaterstons.

I can't seem to reproduce this issue. I wonder if it may be caused by special characters in the path name or something like that. Any chance you could test to see if it works, if you relocate the database.json folder to somewhere else on your machine, perhaps something like: `c:\test\te3folder\database.json` ?

What type of version control system (if any) do you use?

Thanks!

**Comment by JohnnyWinterWaterstons** [comment] 2021-12-16 17:18
I think I figured it out.

The file path didn’t make a difference.

I think it’s user error… I was opening the database.json from file but if I open a model from folder instead, everything works fine.

Not sure if that’s still a bug or how it’s supposed to work, but if I use the correct process it does work I I’d expect.

Thanks
Johnny


Johnny Winter
Senior Data & Analytics Consultant

T: +44 345 094 0945<tel:+443450940945>
M: 07842313292<tel:07842313292>
waterstons.com<https://www.waterstons.com/?utm_source=signature&utm_medium=email&utm_campaign=homepage>
www.waterstons.com/Johnny-Winter

[Waterstons]<waterstons.com>

 ***@***.*** <https://www.linkedin.com/company/waterstons>  ***@***.*** <https://twitter.com/waterstonsltd>  ***@***.*** <https://instagram.com/waterstonsltd>

**Comment by otykier** [comment] 2021-12-16 18:27
Thanks for the clarification. I can reproduce the issue - it's a bug!

**Comment by otykier** [comment] 2021-12-16 21:42
Fixed in [3.1.7](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.7). Thanks for reporting!

**Closed by otykier** 2021-12-16 21:42 UTC
Labels: bug
