### ISSUE TITLE
Filter on data in Preview Data throws an error

### ISSUE THREAD

**Issue by RoelTrommelen** [TabularEditor/TabularEditor3#124] opened 2021-07-07 05:55 UTC
When trying to filter on a date/time column in the following error is thrown.

[Error details.txt](https://github.com/TabularEditor/TabularEditor3/files/6774697/Error.details.txt)

![Screenshot Error](https://user-images.githubusercontent.com/86881692/124706953-67d1f200-def8-11eb-9ec6-2957bae34b04.png)

**Comment by otykier** [comment] 2021-07-07 07:58
Thanks for reporting. I am unfortunately not able to reproduce this. Could you provide a sample of the data in the column that causes this crash?

**Comment by RoelTrommelen** [comment] 2021-07-07 09:11
In DAX Query:
![image](https://user-images.githubusercontent.com/86881692/124729834-14b86900-df11-11eb-8b4b-4e6103737f2b.png)

So this works, also with the date filters.

See attached output from SQL Server with all the unique dates in the fact table (inluding count).
[dates.txt](https://github.com/TabularEditor/TabularEditor3/files/6775887/dates.txt)

**Comment by Stewwe1** [comment] 2021-07-14 15:38
I have the same problem :-)

**Comment by otykier** [comment] 2021-08-06 11:10
Hi @RoelTrommelen and @Stewwe1. Could you check if the issue still persists in [3.0.8](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.8)? Thanks!

**Comment by RoelTrommelen** [comment] 2021-08-06 11:32
Hi Daniel, 

this is ok now

![image](https://user-images.githubusercontent.com/86881692/128503796-84e2f37b-94e2-4514-aa6e-3792bca0504a.png)

Result:
![image](https://user-images.githubusercontent.com/86881692/128503828-c9b77306-1995-4bbd-b633-67fae23d8ed5.png)

However, another issue turned up: the Pivot Grid doesn't work at all. When I open it I notice an error message flashing, but too short to be able to read or capture it. When I try to drag any item to the pviot grid, the program freezes and has to be terminated in the Task Manager. Do you want me to create a new item for this?

Regards,
Roel

**Comment by otykier** [comment] 2021-08-06 12:10
That sounds like a different issue, so please open a new ticket. Any additional info you can provide is appreciated (type of server, and if possible to run a SQL Profiler trace against AS to see if there are any error messages there, when opening the Pivot Grid in TE3 - thanks!)

**Comment by otykier** [comment] 2021-08-10 12:14
Closing this. Pivot Grid issue is tracked here: #166 (fix coming soon!)

**Closed by otykier** 2021-08-10 12:14 UTC
Labels: bug
