### ISSUE TITLE
Creating a calculated Table causes following Error

### ISSUE THREAD

**Issue by stephan-feddersen** [TabularEditor/TabularEditor3#1390] opened 2024-11-05 14:38 UTC
### Description

An item with the same key has already been added. Key: Microsoft.AnalysisServices.Tabular.CalculatedColumn

### Tabular Editor 3 Version

3.18.0.

### Steps to Reproduce

1. Right click Model, Create, Calculated Table
2. Click somewhere else

### Crash Report

Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.18.0 (3.18.0.5749)
OS version: Microsoft Windows NT 10.0.17763.0
Model details: 
		CompatibilityLevel: 1605
	CompatibilityMode: PowerBI
	IsPbiDesktop: False
	SourceType: Folder
	TableCount: 75
	FirstTimeModelLoad: True
	DatabaseNameSHA256: e6e1e239581ee92f20346b17d4d6d1f1fc636ab2d4292ae3
User description: 
Exception message: An item with the same key has already been added. Key: Microsoft.AnalysisServices.Tabular.CalculatedColumn
Exception source: System.Private.CoreLib
Stack trace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Dax.Analyzer.FilterContext.FromRowContexts(DaxBaseNode sourceNode, IEnumerable`1 rowContexts)
   at Dax.Analyzer.FilterContext.Flatten(IEnumerable`1 contextStack, DaxBaseNode sourceNode)
   at Dax.Analyzer.FilterContext.Flatten(DaxBaseNode sourceNode)
   at Dax.Analyzer.EvaluationContext.GetFilterContext()
   at Dax.Analyzer.SemanticAnalyzerDependencyResolver.ResolveMeasureReference(Measure measure, EvaluationContext evaluationContext, String& errorMessage)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.RequestMeasure(Measure measure, Boolean needsTypeInformation)
   at Dax.Analyzer.Ast.MeasureRefNode.Accept(DaxVisitor visitor, ColumnOrMeasureContext context)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[C,T](C context, T node)
   at Dax.Analyzer.Ast.ColumnOrMeasureHelper.VisitMeasure(DaxVisitor visitor, ColumnOrMeasureContext context, Func`1 nodeCreator)
   at Dax.Analyzer.Ast.ColumnOrMeasureHelper.CreateMeasureRefNode(DaxVisitor visitor, ColumnOrMeasureContext context, Measure modelMeasure)
   at Dax.Analyzer.Ast.ColumnOrMeasureHelper.ResolveUnqualifiedReference(DaxVisitor visitor, ColumnOrMeasureContext context, String objName)
   at Dax.Analyzer.Ast.ColumnOrMeasureHelper.ResolveReference(DaxVisitor visitor, ColumnOrMeasureContext context)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.VisitColumnOrMeasure(ColumnOrMeasureContext context)
   at Dax.Analyzer.Internal.DaxParser.ColumnOrMeasureContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at Dax.Analyzer.Internal.DaxParserBaseVisitor`1.VisitColumnOrMeasureRefExpr(ColumnOrMeasureRefExprContext context)
   at Dax.Analyzer.Internal.DaxParser.ColumnOrMeasureRefExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.FunctionNodeBase`1.VisitArg(Int32 argIndex, Boolean canBeBlank, Boolean needsTypeInformation)
   at Dax.Analyzer.Ast.FunctionNode.AcceptCalculate()
   at Dax.Analyzer.Ast.FunctionNode.<>c.<.cctor>b__178_2(FunctionNode n)
   at Dax.Analyzer.Ast.FunctionNode.Accept(DaxVisitor visitor, FunctionExprContext context)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[C,T](C context, T node)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.VisitFunctionExpr(FunctionExprContext context)
   at Dax.Analyzer.Internal.DaxParser.FunctionExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at Dax.Analyzer.Internal.DaxParserBaseVisitor`1.VisitFunctionCallExpr(FunctionCallExprContext context)
   at Dax.Analyzer.Internal.DaxParser.FunctionCallExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.VariableDeclarationNode.AcceptExpression()
   at Dax.Analyzer.Ast.VariableDeclarationBlockNode.Accept(DaxVisitor visitor, VarDeclarationBlockExprContext context)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[C,T](C context, T node)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.VisitVarDeclarationBlockExpr(VarDeclarationBlockExprContext context)
   at Dax.Analyzer.Internal.DaxParser.VarDeclarationBlockExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.VisitObjectExpr(ObjectExprContext context)
   at Dax.Analyzer.Internal.DaxParser.ObjectExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.AstHelper.AnalyzeDax(Model model, String dax, IDependencyResolver dependencyResolver, AnalyzerSettings settings, Boolean measureSelectionObject, Table homeTable, EvaluationContext initialContext)
   at Dax.Analyzer.Ast.AstHelper.AnalyzeMeasure(Measure measure, IDependencyResolver dependencyResolver, AnalyzerSettings settings, EvaluationContext initialContext)
   at Dax.Analyzer.SemanticAnalyzer.Analyze(ReferencingObject obj, Boolean reanalyze, Boolean triggerEvents, EvaluationContext evaluationContext)
   at Dax.Analyzer.SemanticAnalyzerDependencyResolver.ResolveMeasureReference(Measure measure, EvaluationContext evaluationContext, String& errorMessage)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.RequestMeasure(Measure measure, Boolean needsTypeInformation)
   at Dax.Analyzer.Ast.MeasureRefNode.Accept(DaxVisitor visitor, ColumnOrMeasureContext context)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[C,T](C context, T node)
   at Dax.Analyzer.Ast.ColumnOrMeasureHelper.VisitMeasure(DaxVisitor visitor, ColumnOrMeasureContext context, Func`1 nodeCreator)
   at Dax.Analyzer.Ast.ColumnOrMeasureHelper.CreateMeasureRefNode(DaxVisitor visitor, ColumnOrMeasureContext context, Measure modelMeasure)
   at Dax.Analyzer.Ast.ColumnOrMeasureHelper.ResolveUnqualifiedReference(DaxVisitor visitor, ColumnOrMeasureContext context, String objName)
   at Dax.Analyzer.Ast.ColumnOrMeasureHelper.ResolveReference(DaxVisitor visitor, ColumnOrMeasureContext context)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.VisitColumnOrMeasure(ColumnOrMeasureContext context)
   at Dax.Analyzer.Internal.DaxParser.ColumnOrMeasureContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at Dax.Analyzer.Internal.DaxParserBaseVisitor`1.VisitColumnOrMeasureRefExpr(ColumnOrMeasureRefExprContext context)
   at Dax.Analyzer.Internal.DaxParser.ColumnOrMeasureRefExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.BinaryNode.Accept(DaxVisitor visitor, BinaryExprContext context)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[C,T](C context, T node)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.VisitBinaryExpr(BinaryExprContext context)
   at Dax.Analyzer.Internal.DaxParser.BinaryExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.BinaryNode.Accept(DaxVisitor visitor, BinaryExprContext context)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[C,T](C context, T node)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.VisitBinaryExpr(BinaryExprContext context)
   at Dax.Analyzer.Internal.DaxParser.BinaryExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.FunctionNodeBase`1.VisitArg(Int32 argIndex, Boolean canBeBlank, Boolean needsTypeInformation)
   at Dax.Analyzer.Ast.FunctionNode.FilterAcceptor.Accept(FunctionNode node)
   at Dax.Analyzer.Ast.FunctionNode.Accept(DaxVisitor visitor, FunctionExprContext context)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[C,T](C context, T node)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.VisitFunctionExpr(FunctionExprContext context)
   at Dax.Analyzer.Internal.DaxParser.FunctionExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at Dax.Analyzer.Internal.DaxParserBaseVisitor`1.VisitFunctionCallExpr(FunctionCallExprContext context)
   at Dax.Analyzer.Internal.DaxParser.FunctionCallExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.FunctionNodeBase`1.VisitArg(Int32 argIndex, Boolean canBeBlank, Boolean needsTypeInformation)
   at Dax.Analyzer.Ast.FunctionNodeBase`1.VisitIteratorArg(Int32 argIndex, Boolean allowKeepFilters)
   at Dax.Analyzer.Ast.FunctionNode.SelectColumnsAcceptor.Accept(FunctionNode node)
   at Dax.Analyzer.Ast.FunctionNode.Accept(DaxVisitor visitor, FunctionExprContext context)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[C,T](C context, T node)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.VisitFunctionExpr(FunctionExprContext context)
   at Dax.Analyzer.Internal.DaxParser.FunctionExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at Dax.Analyzer.Internal.DaxParserBaseVisitor`1.VisitFunctionCallExpr(FunctionCallExprContext context)
   at Dax.Analyzer.Internal.DaxParser.FunctionCallExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.VariableDeclarationNode.AcceptExpression()
   at Dax.Analyzer.Ast.VariableDeclarationBlockNode.Accept(DaxVisitor visitor, VarDeclarationBlockExprContext context)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[C,T](C context, T node)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.VisitVarDeclarationBlockExpr(VarDeclarationBlockExprContext context)
   at Dax.Analyzer.Internal.DaxParser.VarDeclarationBlockExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.VisitObjectExpr(ObjectExprContext context)
   at Dax.Analyzer.Internal.DaxParser.ObjectExprContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(IParseTree tree)
   at Dax.Analyzer.Ast.AstHelper.AnalyzeDax(Model model, String dax, IDependencyResolver dependencyResolver, AnalyzerSettings settings, Boolean measureSelectionObject, Table homeTable, EvaluationContext initialContext)
   at Dax.Analyzer.Ast.AstHelper.AnalyzeCalculatedTable(CalculatedPartitionSource partitionSource, IDependencyResolver dependencyResolver, AnalyzerSettings settings, EventHandler`1 calculatedTableChange)
   at Dax.Analyzer.SemanticAnalyzer.Analyze(ReferencingObject obj, Boolean reanalyze, Boolean triggerEvents, EvaluationContext evaluationContext)
   at Dax.Analyzer.SemanticAnalyzerExtension.Analyze(ISemanticAnalyzer analyzer, CalculatedPartitionSource calculatedPartitionSource, Boolean reanalyze, Boolean triggerEvents)
   at Dax.Analyzer.SemanticAnalyzer.FullSemanticAnalysisInternal(Boolean verbose, Boolean expandMeasures)
   at Dax.Analyzer.SemanticAnalyzer.FullSemanticAnalysis(Boolean verbose)
   at Dax.Analyzer.SemanticAnalyzer.FullSemanticAnalysisWithEvents(Object canReanalyze)
   at Dax.Analyzer.SemanticAnalyzer.<>c__DisplayClass109_0.<FullSemanticAnalysisBackground>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dax.Analyzer.SemanticAnalyzer.FullSemanticAnalysisBackground(Boolean canReanalyze)
   at TabularEditor.TOMWrapper.TabularModelHandler.PerformSemanticAnalysis()
   at TabularEditor.UI.Services.TomSelectionValidator.ViewModel_SelectionChanging(Object sender, SelectionChangingEventArgs e)
   at TabularEditor.UI.ViewModels.TabularExplorerViewModel.OnSelectionChanging(Selection newValue, Selection oldValue)
   at TabularEditor.UI.ViewModels.TabularExplorerViewModel.set_Selection(Selection value)
   at TabularEditor.UI.Views.TabularExplorerView.treeList_SelectionChanged(Object sender, EventArgs e)
   at DevExpress.XtraTreeList.TreeList.RaiseSelectionChanged()
   at DevExpress.XtraTreeList.TreeList.OnSelectionChanged()
   at DevExpress.XtraTreeList.TreeListMultiSelection.Changed(Boolean needRaiseEvent)
   at DevExpress.XtraTreeList.TreeListMultiSelection.EndSelect()
   at DevExpress.XtraTreeList.TreeList.EndSelection()
   at TabularEditor.UI.DxExtensions.TreeListCustomCellSelect.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   at TabularEditor.UI.DxExtensions.TreeListCustomPadding.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
Modules loaded: 
		TabularEditor3.dll

### Windows Version

Windows Server 2019

**Comment by otykier** [comment] 2024-11-06 00:57
Hi, thanks for reporting this. Unfortunately, we’re not able to reproduce this issue on our side.

Is there any chance you could send us the Model.bim file of the model where you’re observing this behavior? support@tabulareditor.com

**Comment by otykier** [comment] 2024-11-06 13:24
FYI, this is the same as #1393. Fix is coming ASAP! Please downgrade to [3.17.1](https://docs.tabulareditor.com/te3/other/release-notes/3_17_1.html?tabs=downloads) for the time being.

**Comment by otykier** [comment] 2024-11-11 12:41
This is now fixed in [3.18.1](https://docs.tabulareditor.com/te3/other/release-notes/3_18_1.html?tabs=downloads). Thanks for reporting this and for your patience while we worked on a fix.

**Closed as completed by otykier** 2024-11-11 12:41 UTC
Labels: issue: bug
