### ISSUE TITLE
DAX Query window times out - loses connection

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#806] opened 2023-01-31 19:02 UTC
I often get the error "The '\<eupi>_guid here_\</euip>' session ID cannot be found. Either the session doesn't exist or has already expired."

I am not sure what the timeout period is, but certainly less than an hour on Premium capacity. I don't have this issue with DAX Studio. 

Workflow issues this impacts is I was in the middle of a debugging session from a DAX query from a viz and had the query pre-filtered to a specific set of rows I was looking at. ~Had to largely start over. Not the end of the world, but not ideal.~ Had to totally start over. Even after closing the debugger session, the dax query, and opening a new DAX query and running it, the debugger reported the _'\<euip>guid..._ error for every value.

Is there any way for TE to send a keep-alive signal to the service, or is there something else going on here?

**Comment by mlonsk** [comment] 2023-02-02 08:54
Hi Ed

You are right this is an issue. We are aware of it. See also #650 and #803 
I will close this as a duplicate of those, but that you for reporting and being an active part of making TE3 a better tool!

**Closed by mlonsk** 2023-02-02 08:54 UTC
