### ISSUE TITLE
Intellisense doesn't work with a loaded DAX Script file

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#352] opened 2022-01-19 14:36 UTC
Tabular Editor 3.1.7

I loaded a text file (extension .te3daxs) that has a script to create 2 calculation groups. The intellisense doesn't work correctly. No red wavy lines show up if there are issues. When I run the script, it will fail and say "please fix DAX script errors before applying the script to the model" and then move the cursor to the first error. Once I fix the first error, then Intellisense kicks in and shows me all errors.

If I create a new blank DAX script and paste the code in, Intellisense works from the start, so it seems to only be when you open the script from a file.

**Comment by otykier** [comment] 2022-01-19 18:58
Thanks for reporting - we'll look into it!

**Comment by otykier** [comment] 2022-01-19 22:15
We were unable to reproduce this issue.

Any chance you could send a repro to support@tabulareditor.com? Thanks!

**Comment by edhans** [comment] 2022-01-19 23:37
I sent a screen recording from my P3 Adaptive account. Let me know if that is sufficient or if you need a PBIX file too.

_________________________
Ed Hansberry ​
Microsoft MVP - Data Platform/Power BI
www.ehansalytics.com<file:///var/containers/Bundle/Application/86D1ED1B-000D-4277-9618-B915917F8BF6/Spark.app/smi-composer.bundle/www.ehansalytics.com>
________________________________

**Comment by otykier** [comment] 2022-01-26 12:25
Hi @edhans - is this issue still present in [TE 3.2.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.0)?

**Comment by edhans** [comment] 2022-01-26 16:27
Yes. I just tested it. The Intellisense didn't kick in and tell me there was an error until I changed the first invalid field. Then it showed all errors in the DAX script.

**Comment by otykier** [comment] 2022-01-26 17:26
Thanks - we’ll look into it.

**Comment by otykier** [comment] 2022-01-28 10:44
This is now fixed in [3.2.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.1). Thanks for reporting!

**Closed by otykier** 2022-01-28 10:44 UTC
Labels: bug
