### ISSUE TITLE
Crashes On Every Connection to Model (3.3.1)

### ISSUE THREAD

**Issue by pugliathomas** [TabularEditor/TabularEditor3#586] opened 2022-06-28 00:50 UTC
The latest release (https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.1) now no longer allows me to connect to a model. The application crashes every time. 

I have tried both a local model and a Power BI Service model, and tried on two different computers, one running windows 10 and the other Windows 11.

Thanks!

**Comment by otykier** [comment] 2022-06-28 01:07
Possible duplicate of #571 - do you see anything in the Windows Event Viewer as described in the last comment on that thread?

**Comment by otykier** [comment] 2022-06-28 01:21
Issue might be related to telemetry. Please try to disable [Help improve Tabular Editor by collecting anonymous usage data](https://docs.tabulareditor.com/te3/features/preferences.html#tabular-editor--updated-and-feedback)

**Comment by pugliathomas** [comment] 2022-06-28 01:43
Tried this to disable, closed TE3 and opened up again. 

```
Level	Date and Time	Source	Event ID	Task Category
Error	6/27/2022 8:35:28 PM	.NET Runtime	1026	None	"Application: TabularEditor3.exe
CoreCLR Version: 6.0.622.26707
.NET Version: 6.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'TabularEditor.Shared.Services.SensitiveProcessor' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void TabularEditor.Utils.TrieReplaceOptions.set_StripPiiLabels(Boolean)'.
   at TabularEditor.Shared.Services.SensitiveProcessor..cctor()
   --- End of inner exception stack trace ---
   at TabularEditor.Shared.Services.SensitiveProcessor.StripSensitive(String original)
   at TabularEditor.UI.Dialogs.ErrorReportDialog.GetErrorReport(Exception exception, String userMessage)
   at TabularEditor.Program.Application_ThreadException(Object sender, ThreadExceptionEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at TabularEditor.Program.Main()
"
Error	6/27/2022 7:56:38 PM	.NET Runtime	1026	None	"Application: tabulareditor3.exe
CoreCLR Version: 6.0.622.26707
.NET Version: 6.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'TabularEditor.Shared.Services.SensitiveProcessor' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void TabularEditor.Utils.TrieReplaceOptions.set_StripPiiLabels(Boolean)'.
   at TabularEditor.Shared.Services.SensitiveProcessor..cctor()
   --- End of inner exception stack trace ---
   at TabularEditor.Shared.Services.SensitiveProcessor.StripSensitive(String original)
   at TabularEditor.UI.Dialogs.ErrorReportDialog.GetErrorReport(Exception exception, String userMessage)
   at TabularEditor.Program.Application_ThreadException(Object sender, ThreadExceptionEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at DevExpress.Utils.Drawing.Helpers.NativeMethods.UnsafeNativeMethods.DefSubclassProc(IntPtr hWnd, IntPtr Msg, IntPtr wParam, IntPtr lParam)
   at DevExpress.Utils.Drawing.Helpers.NativeMethods.DefSubclassProc(IntPtr hWnd, IntPtr Msg, IntPtr wParam, IntPtr lParam)
   at DevExpress.Utils.Drawing.Helpers.Win32SubclasserFactory.Win32Subclasser.SubClassProcInner(IntPtr hWnd, IntPtr Msg, IntPtr wParam, IntPtr lParam, IntPtr uIdSubclass, IntPtr dwRefData)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at TabularEditor.Program.Main()
"
```

**Comment by pugliathomas** [comment] 2022-06-28 01:46
After disabling the option, no more .Net Runtime, but getting Application Errors:

```
Log Name:      Application
Source:        Application Error
Date:          6/27/2022 8:43:47 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A

Description:
Faulting application name: FileCoAuth.exe, version: 22.121.605.2, time stamp: 0x269af7b7
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1741, time stamp: 0xe9b4a91b
Exception code: 0xc0000005
Fault offset: 0x0000000000062994
Faulting process id: 0x8b54
Faulting application start time: 0x01d88a902b1d8c1b
Faulting application path: C:\Program Files\Microsoft OneDrive\22.121.0605.0002\FileCoAuth.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b19c8d5c-d7fc-43e2-8a15-720ab288ee41
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-28T01:43:47.4296043Z" />
    <EventRecordID>94549</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer></Computer>
    <Security />
  </System>
  <EventData>
    <Data>FileCoAuth.exe</Data>
    <Data>22.121.605.2</Data>
    <Data>269af7b7</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.1741</Data>
    <Data>e9b4a91b</Data>
    <Data>c0000005</Data>
    <Data>0000000000062994</Data>
    <Data>8b54</Data>
    <Data>01d88a902b1d8c1b</Data>

    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>b19c8d5c-d7fc-43e2-8a15-720ab288ee41</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

```
Log Name:      Application
Source:        Application Error
Date:          6/27/2022 8:43:51 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A

Description:
Faulting application name: FileCoAuth.exe, version: 22.121.605.2, time stamp: 0x269af7b7
Faulting module name: ntdll.dll, version: 10.0.19041.1741, time stamp: 0x77755782
Exception code: 0xc00000fd
Fault offset: 0x000000000002aa2e
Faulting process id: 0x8bd4
Faulting application start time: 0x01d88a908449e08e
Faulting application path: C:\Program Files\Microsoft OneDrive\22.121.0605.0002\FileCoAuth.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 2f8cc8db-e4a5-400a-b39a-2cb8651d4877
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-28T01:43:51.4924833Z" />
    <EventRecordID>94552</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer></Computer>
    <Security />
  </System>
  <EventData>
    <Data>FileCoAuth.exe</Data>
    <Data>22.121.605.2</Data>
    <Data>269af7b7</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.19041.1741</Data>
    <Data>77755782</Data>
    <Data>c00000fd</Data>
    <Data>000000000002aa2e</Data>
    <Data>8bd4</Data>
    <Data>01d88a908449e08e</Data>
    <Data>C:\Program Files\Microsoft OneDrive\22.121.0605.0002\FileCoAuth.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data>
    <Data>2f8cc8db-e4a5-400a-b39a-2cb8651d4877</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by otykier** [comment] 2022-06-28 06:44
@pugliathomas , @palombiechamonix could you try the following, please:

1. Uninstall Tabular Editor 3
2. Make sure the `%ProgramFiles%\Tabular Editor 3` folder is empty or gone (if any files are left please let me know which ones, before deleting them)
3. Reinstall Tabular Editor 3

**Comment by PalombieChamonix** [comment] 2022-06-28 08:52
Here are the files remaining :
![image](https://user-images.githubusercontent.com/91263359/176137210-7cbae2ed-f212-4220-b702-0b536f98f897.png)

**Comment by PalombieChamonix** [comment] 2022-06-28 09:00
IT's working out fine !!!! HOURA !!!

**Comment by pugliathomas** [comment] 2022-06-28 12:25
That worked for me as well. Did have to delete about 20 files, will send list shortly

**Comment by otykier** [comment] 2022-06-28 14:05
The installer in [3.3.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.2) now correctly updates files from previous installations.

**Closed by otykier** 2022-06-28 14:05 UTC
Labels: bug

**Comment by otykier** [comment] 2022-06-28 14:18
@pugliathomas this is a different issue. I've copied it here: #587
