### ISSUE TITLE
Can't Obtain Account Information when saving

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1317] opened 2024-06-14 22:43 UTC
### Description

Could be coincidence, or something new in 3.16. This started for me yesterday after upgrading. When I save a model, probably 25% of the time I get the following error when trying to save against an XMLA endpoint to a Power BI Premium Capacity.

![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/5a293e30-78a1-4276-a077-7797cddac1ff)

Saving again so far has always fixed it, so it isn't preventing work from getting done, just annoying.

### Tabular Editor 3 Version

3.16

### Windows Version

11

**Comment by mlonsk** [comment] 2024-06-17 08:28
Hi @edhans 

That does sound annoying. 
I have not been able to reproduce it by making random changes and saving it. Are you making any specific changes at that point that you are saving?

**Comment by edhans** [comment] 2024-06-17 10:59
Not that I can think of. 99% of what I am doing is just adding or changing measures. The model otherwise is pretty stable.

**Comment by mlonsk** [comment] 2024-06-17 11:22
Could you share a Session ID (Help -> About Tabular Editor) with us the next time it happens, either here or at support@tabulareditor.com ? We can then try to look at the telemetry to investigate what is happening.

**Comment by edhans** [comment] 2024-06-17 13:49
It just happened 30 seconds ago. Session ID d1c76377-c61c-4759-a8d3-d1d2322ca003

I had just duplicated a measure and saved the model.

**Comment by edhans** [comment] 2024-06-17 18:04
Just happened again. Made a very small change to a measure. Save, error shown above, click ok, then save and it works. It has never not worked on the 2nd save. Same session ID as above.

**Comment by otykier** [comment] 2024-06-18 07:38
Thanks Ed, we see the logs now. It seems to be a problem in [AMO/TOM v. 19.80.0](https://www.nuget.org/packages/Microsoft.AnalysisServices.NetCore.retail.amd64/19.80.0) which we started using in version 3.16.0 of Tabular Editor. We have reached out to Microsoft to better understand what's going on.

**Comment by edhans** [comment] 2024-06-18 11:14
Thanks Daniel. I was following the thread at #1322 and wondered if it was related. 🤨

**Comment by mlonsk** [comment] 2024-06-18 11:22
It certainly seems to be; as Daniel said in #1322, we are considering our next steps.

**Comment by otykier** [comment] 2024-06-18 13:25
Hi @edhans 
We have a new build ready where we've rolled back AMO/TOM to 19.79.1.1. This is the same version that we used in TE 3.15.0.

Could you give this new build a shot and see if this fixes the issue for you? Thanks!

Download options:

- [64 bit installer](https://cdn.tabulareditor.com/files/TabularEditor.3.16.2.Installer.x64.exe)
- [64 bit portable](https://cdn.tabulareditor.com/files/TabularEditor.3.16.2.x64.zip)
- [32 bit installer](https://cdn.tabulareditor.com/files/TabularEditor.3.16.2.Installer.x86.exe)
- [32 bit portable](https://cdn.tabulareditor.com/files/TabularEditor.3.16.2.x86.zip)

(Release notes identical to [3.16.1](https://docs.tabulareditor.com/te3/other/release-notes/3_16_1.html?tabs=downloads) with the addition that AMO/TOM has been downgraded to 19.79.1.1)

**Comment by edhans** [comment] 2024-06-18 13:37
Will do. Installing now but won't be getting to work on models for a few hours this morning.

**Comment by edhans** [comment] 2024-06-18 19:53
FYI @otykier - I've been working for about 3 straight hours now and rock solid stable. This issue has not come back since upgrading to 3.16.2, so yeah, that new component from MS is a mess. Thanks!

**Comment by mlonsk** [comment] 2024-06-19 08:32
Thank you for testing @edhans, much appreciated. 

We have just publicly released 3.16.2 and will close this issue.

**Closed as completed by mlonsk** 2024-06-19 08:32 UTC
Labels: issue: bug
