### ISSUE TITLE
Unable to upload model to DAX Optimizer - Field Parameter blocks it

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1376] opened 2024-09-30 23:45 UTC
### Description

I get the error in the screenshot below saying it cannot load a model to the DAX Optimizer because a column is part of a composite key but not all columns are included in an expression or dependent expression. I have a few measures looking at that FP, and one relationship.

This only happens when Read Stats from Data is selected in preferences, which is required for DAX Optimizer.

Removing the measures doesn't fix it. Deleting the relationship does. However that breaks the model as measures and the report layer need that. It is a 2nd field parameter that is on the many side (the one in the error is on the 1 side) that allows the FP causing the error to dynamically change the fiscal periods shown depending on if Week, Month, Quarter, or Year is selected.

Is this an error in the model itself, or should gathering stats work?

FYI - DAX Studio will do this and not report an error.

### Tabular Editor 3 Version

3.17.0

### Screenshots

![image](https://github.com/user-attachments/assets/4ba82570-ecda-4983-8aaa-b3ecabf6e840)

### Steps to Reproduce

create a 1 to many relationship with the first field in a field parameter, with the FP being the 1 side.
Try to run Vertipaq analyzer with "read stats from data" enabled.

### Windows Version

11

**Comment by otykier** [comment] 2024-10-01 10:16
Thanks Ed. I believe this issue will be solved with the newest version of VertiPaq Analyzer, which will be included in our October update of TE3 in a few weeks from now.

**Comment by otykier** [comment] 2024-10-01 10:16
cc @albertospelta to confirm

**Comment by albertospelta** [comment] 2024-10-01 19:50
@otykier, unfortunately, the latest version of VertiPaq Analyzer has only partially resolved the issue and a similar error exists in the relationship stats extractor. We have been able to reproduce the error, and the fix should be available in a few days.

**Comment by otykier** [comment] 2024-10-02 07:40
@albertospelta I see - thanks. Let me know when the update is available :)

**Comment by albertospelta** [comment] 2024-10-02 18:55
@otykier the fix has been released in version [1.7.2](https://github.com/sql-bi/VertiPaq-Analyzer/releases/tag/v1.7.2)

**Comment by otykier** [comment] 2024-11-11 12:45
Closing this ticket since the issue has been fixed in 3.18.0 (and [3.18.1](https://docs.tabulareditor.com/te3/other/release-notes/3_18_1.html?tabs=downloads)).

**Closed as completed** 2024-11-11 12:44 UTC
Labels: issue: bug
