### ISSUE TITLE
Bug in the DAX Editor?

### ISSUE THREAD

**Issue by CraigsterT** [TabularEditor/TabularEditor3#864] opened 2023-03-29 22:48 UTC
There seems to be a new issue in 3.5.1. When I am typing out a simple measure , for instance , Sales YTD , I start the measure CALCULATE( [Sales Amount] , and at this stage the closing parenthesis for CALCULATE()  suddenly vanishes and has to be retyped. Is this a bug in the editor ?

**Comment by otykier** [comment] 2023-03-30 06:16
@CraigsterT we're not able to reproduce what you describe. It would be helpful if you could share a gif or short video recording of how to trigger this bug.

**Comment by DBojsen** [comment] 2023-03-31 07:05
Thank you @edhans - I can also repro now with your description.
I'll add to our list of bugs.

BR David - TE3 Support

**Comment by CraigsterT** [comment] 2023-04-01 13:17
Thanks Ed , that's exactly the same experience that I had.  I should have
been more accurate and mentioned that this occurred after trying to nest
another function ,  but it was a little late in the day. It's a little
annoying. More perhaps because you're not used to it behaving like that and
it does slow you down a little. So , no pressure on a fix for this one
Guys. Only joking.

**Comment by otykier** [comment] 2023-04-02 12:08
@CraigsterT as a workaround until we get this fixed, it may help to disable **Auto-indent** and/or **Auto-brace** through **Tools > Preferences > DAX Editor > Auto formatting**

**Comment by CraigsterT** [comment] 2023-04-03 07:49
Thanks Daniel , that's very much appreciated. I will give this a try and
let you know.

**Comment by DBojsen** [comment] 2023-04-19 20:54
Hi @CraigsterT & @edhans 

This should be fixed in [3.6.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.6.0).
Thanks for reporting.

BR David - TE3 Support

**Closed by DBojsen** 2023-04-19 20:54 UTC
Labels: bug

**Comment by CraigsterT** [comment] 2023-04-19 22:36
It certainly is ! Best news of the week.   Thanks BR David & Daniel . It's very much appreciated .
