### ISSUE TITLE
Macro Recorder doesn't capture deleted Measure or M Tables

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#1336] opened 2024-06-26 20:50 UTC
### Description

When using Macro recorder if you delete Measures, M Tables, Calculated Columns then they aren't captured, in fact if you delete the Fact table but then use the Revert and Reload metadata option the UI starts giving errors on the Fact Table even though changes weren't made to the SSAS Tabular database.

Is this intended behaviour? Because I haven't used Macro Recorder in years and I use Visual Studio for C# related stuff and then just move the script into TE.

### Tabular Editor 3 Version

3.2.16

### Windows Version

Windows 10

**Comment by otykier** [comment] 2024-06-27 08:43
Hi @SharmaAntriksh 
I can confirm that there is a bug in which the macro recorder doesn't generate code for deleting objects. We'll make sure this is fixed.

As for the other issue you mentioned (errors on the fact table), I am not able to reproduce this. Could you specify exactly the steps taken to trigger this issue? Thank you!

**Comment by SharmaAntriksh** [comment] 2024-06-27 12:16
Thanks, I figured out that if you have a Details Rows Expression code and you delete the table in which it resides and then revert the change then it throws error.


https://github.com/TabularEditor/TabularEditor3/assets/73054674/0df6a1a9-e428-4bfc-92b5-50f561609482

**Comment by otykier** [comment] 2024-06-27 12:28
Thanks for these additional details. This seems to be a separate bug, unrelated to the macro recorder. We'll look into that as well!

**Comment by SharmaAntriksh** [comment] 2024-06-27 12:37
Yup, until yesterday I thought it was happening while recording Macro so I added in the same issue :)

**Comment by otykier** [comment] 2024-08-15 11:20
This is fixed in [3.17.0](https://docs.tabulareditor.com/te3/other/release-notes/3_17_0.html?tabs=downloads). Thanks again for reporting!

**Closed as completed by otykier** 2024-08-15 11:20 UTC
Labels: issue: bug
