### ISSUE TITLE
Properties panel not showing?

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#375] opened 2022-01-28 22:16 UTC
not sure why, but the properties panel is no longer showing 

https://user-images.githubusercontent.com/40455069/151629266-f87909f5-a8b9-4a19-ae2f-d617e17fb0f8.mp4

**Comment by otykier** [comment] 2022-01-28 22:19
Can you open it through the **View** menu or by restoring the Default layout through the **Window** menu?

**Comment by bernatagulloesbrina** [comment] 2022-01-28 22:26
Through the view layout I can see it, but now is like the same level as TOM explorer
I can't right click a thing and go to its properties 
Reseting layout through window menu apparently does nothing. 

https://user-images.githubusercontent.com/40455069/151629822-683c8180-1dcb-4ed1-aefd-d8a29273538f.mp4

Deleting the layouts.json file does the trick and everything goes back to normal, but then I have to build for the Nth time my macro toolbar...

**Comment by otykier** [comment] 2022-01-28 22:34
You know you can drag the properties window to make it appear below the TOM Explorer, right? But in any case, we’ll look into the properties shortcut not working.

Btw, the “Reset window layout” is for the documents (misleading text, I know). You should choose “Default layout” to bring the layout back to its original state.

**Comment by bernatagulloesbrina** [comment] 2022-01-29 06:53
I did try to get it there, but I could not manage. Only got it on the
bottom of the screen but with the full width, which I did not want. I'll
try your hints, and if nothing works, I'll build again my macro toolbar
(maybe custom toolbars could be stored in a different file?)

Regards

**Comment by bernatagulloesbrina** [comment] 2022-01-29 13:11
OK good news and bad news.
The good: Default Layout does bring properties back to its place
The bad: It deletes the custom toolbar

Maybe it's time to save layouts somewhere? 

I'm sure you'll come up with a fix soon

**Comment by otykier** [comment] 2022-02-07 12:47
Toolbars will be saved together with the layout of the windows. This is by design and will not be changed.

But the Properties window not showing up when clicking on "Properties" is a bug - that will be fixed soon.

**Comment by otykier** [comment] 2022-02-17 08:11
Fixed in [3.2.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.2), thanks for reporting.

**Closed by otykier** 2022-02-17 08:11 UTC
Labels: bug
