### ISSUE TITLE
A

### ISSUE THREAD

**Issue by pugliathomas** [TabularEditor/TabularEditor3#585] opened 2022-06-28 00:50 UTC
The latest release (https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.1) now no longer allows me to connect to a model. The application crashes every time. 

I have tried both a local model and a Power BI Service model, and tried on two different computers, one running windows 10 and the other Windows 11.

Thanks!

**Comment by otykier** [comment] 2022-06-28 01:07
Duplicate of #586

**Closed by otykier** 2022-06-28 01:07 UTC
