### ISSUE TITLE
Auto generated "\\" characters in a connection string for Databricks

### ISSUE THREAD

**Issue by ZdenekSoldan** [TabularEditor/TabularEditor3#1221] opened 2024-01-26 07:49 UTC
### Description

After connecting to Databricks and publishing the model to Power BI Service, I cannot connect to Power BI Gateway because TE3 automatically generated "\\" in the connection string.  The final connection string looks like this:

But PBI GW cannot be created in this format.

### Tabular Editor 3 Version

3.13

### Screenshots

![image](https://github.com/TabularEditor/TabularEditor3/assets/26428515/b4c9f5c4-aabd-4722-a94e-a99cf79db122)

**Comment by mlonsk** [comment] 2024-02-01 08:11
Hi @ZdenekSoldan 
We are looking into what could be causing this behaviour and will get back to you when we have an update

**Comment by otykier** [comment] 2024-05-01 08:00
Hi @ZdenekSoldan 
Apologies for the long turnaround on this. Could you let us know what the connection string looks like, when created through Power BI Desktop? We're trying to understand what exactly the difference is. Thank you!

**Comment by otykier** [comment] 2024-08-02 11:09
Closing this, as we are not able to reproduce the issue. Kindly let us know if you're still facing this issue using the newest version of Tabular Editor 3.

**Closed as completed by otykier** 2024-08-02 11:09 UTC
Labels: issue: under review
