### ISSUE TITLE
Cannot Import Table from SQL Server

### ISSUE THREAD

**Issue by blynchdata** [TabularEditor/TabularEditor3#69] opened 2021-06-09 16:58 UTC
Using the 30-day free trial, there is no option to Import a table and when I manually type a query in to the Partition query editor it won't let me save. The error that pops up is in a dialog box that is too small to read the whole error and the dialog box cannot be made bigger. 

Is this by design for the free trial?

Thank you.
Brad

**Comment by otykier** [comment] 2021-06-09 17:03
Import Table wizard is not yet available in any edition. However, the process you described should work. What type of Analysis Services instance are you using? Could you post a screenshot of the error message? Thanks.

**Comment by blynchdata** [comment] 2021-06-09 17:13
![Tabular Editor 3 Query Editor](https://user-images.githubusercontent.com/2792035/121399394-3b33b600-c90b-11eb-9d44-490115b27c0f.jpg)

The model is on SQL Server 2016 SSAS Tabular.

Here is an error after trying to save a SELECT * FROM <a SQL Server 2016 view>.

**Comment by otykier** [comment] 2021-06-10 07:23
I'm not able to reproduce the issue on a SSAS 2016 model. Here's what I tried:

1. Connect to an existing model on SSAS 2016
2. Right-click on "Tables", then "Create" > "Table"
3. Navigated to the partition of the newly added table, then typed in something like `SELECT * FROM blah`
4. Saved the model (ctrl+S). All good.

![image](https://user-images.githubusercontent.com/8976200/121482067-0ee06e00-c9cd-11eb-8819-964b159501d2.png)

A couple of things to check:

- Is the partition you added a *legacy* partition that uses *Import* mode, as in the screenshot above? "Mode" property on the partition should be set to "Import" or "Default" as in the screenshot above.
- Does the partition have a data source specified (on my screenshot I'm using the "SqlServer localhost" data source)?

The dialog box issue is a general issue with the UI, which can happen when display resolution/scaling is changed mid-session, for example if an external monitor is connected to your PC. Typically, this issue can be resolved by logging out of Windows and logging back in (if this doesn't solve the issue with the size of the dialog box, please open a separate ticket for that - thanks!)

**Comment by blynchdata** [comment] 2021-06-10 15:22
I have verified this partition is in Default Mode and I have now also tried it on Import mode just in case. 

![image](https://user-images.githubusercontent.com/2792035/121551601-a42b3480-c9c4-11eb-9a89-bc2e17dfef53.png)


Thank you for that tip on the monitors, I moved to my smaller main laptop monitor and was able to capture the full error output:
![image](https://user-images.githubusercontent.com/2792035/121550998-1b13fd80-c9c4-11eb-9f52-f93946d32fc5.png)

The partition does have a data source. It is the same data source that is in my model. When I go to Tabular Editor 2, that same data source is used to pull in new tables and views. 

I'm researching this Analysis Services error now as I don't understand it. I have tried both "Select *..." and "Select <column names"..." and both return the error, "Has no columns..."

Thank you for your help!

**Comment by blynchdata** [comment] 2021-06-10 15:27
I just created a new, fresh data source from within Tabular Editor 3 to the SQL Server source, tested it successfully within that wizard. 

When I create the same DIM_Date table with that query from above, the same error persists. How odd! I must be missing something right in front of me.

**Comment by otykier** [comment] 2021-06-10 15:37
Apparently on SSAS 2016, you can't have a table without any columns. So make sure to add a column manually (right-click on the table > Create > Data Column) before saving.

**Comment by blynchdata** [comment] 2021-06-10 15:46
This now works. I couldn't find that Add Data Column option, thank you.

In each column, I had to also manually add the Source Column. Do you think this is also native to SSAS 2016 or is it a difference between Tabular Editor 2 vs Tabular Editor 3 somehow?

![image](https://user-images.githubusercontent.com/2792035/121555634-06396900-c9c8-11eb-8997-9969d60a2857.png)

Regardless, since I have a path to pulling in a new table now in version 3, even with manually adding column names, I can move forward. 

Thank you so much for these tools, they are really life savers from having to work in Visual Studio.

**Comment by samusaran** [comment] 2021-06-23 12:43
> 
> 
> Import Table wizard is not yet available in any edition. However, the process you described should work. What type of Analysis Services instance are you using? Could you post a screenshot of the error message? Thanks.

Will it be available? Will it be limited to legacy data sources?
I work in consulting and adding tables is common, with some clients being stuck with SSAS 2016, and others being on more recent versions.
For us it could be a deal breaker.

**Comment by otykier** [comment] 2021-06-23 13:48
> Will it be available? 
Yes! Expected to arrive next week!

> Will it be limited to legacy data sources?
No! The reason for the delay was that I wanted to add support for Power Query partitions.

**Comment by samusaran** [comment] 2021-06-23 13:54
That's awesome to hear. We have some clients that uses Oracle as SSAS data source, so we'll test it as soon as it releases!

**Comment by otykier** [comment] 2021-09-05 23:18
Import Table Wizard is available as of [3.1.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.1.0). Feel free to open a new ticket if you have any questions/issues with it.

**Closed by otykier** 2021-09-05 23:18 UTC
Labels: backlog
