### ISSUE TITLE
[Issue] False Circular dependancies detected 

### ISSUE THREAD

**Issue by luukhendrikscordstrap** [TabularEditor/TabularEditor3#920] opened 2023-06-20 12:49 UTC
**Describe the issue**
The messages view in TE3 Shows Circular Dependencies in some measures (especially ones that use Field parameters in the measures)
shows Errors. Opening the measure and adding a space lets TE3 Reconsider its position. all the errors disappear. Whenever I open the dataset from folder the next time they re-appear. Making my messages view basically useless because one measure gets about 20 errors. 

** Which version are you currently using? **
Tabular Editor 3 edition: Business

**To Reproduce**
Connected to PPU "large Datasets" with a workspace and saving offline to folder for git

Whenever the dataset is opened in Tabular Editor 3 From Folder and is connected to a workspace dataset. Making the errors disappear is easy. Just open the faulted measure, place a space on any spot and remove it. the Expression editor checks everything out again and the errors in that measure disappear. This needs to happen for all the measures plagued by this error.  

**Expected behavior**
The messages shouldn't pop up at all. 

**Screenshots**
![image](https://github.com/TabularEditor/TabularEditor3/assets/128694820/f31c80f0-e3c2-4058-b491-a12929e6ff7b)

**Desktop (please complete the following information):**
Windows 10

**Comment by otykier** [comment] 2023-06-20 13:08
Thanks for reporting this. Unfortunately, we're not able to reproduce this. Any chance you could share the model.bim (just the model metadata - no actual data needed) with us? If so, please send to support@tabulareditor.com and refer to this issue, https://github.com/TabularEditor/TabularEditor3/issues/920

Thanks!

**Comment by otykier** [comment] 2023-06-26 09:23
Hi Luuk,
Just an update on this: It turns out to be a bug in the way we analyze DAX expressions that use the [`NAMEOF`](https://dax.guide/nameof) function. A fix unfortunately didn't make it for our June release (which is available now), however, this will be fixed in the next release (expected mid-July).
If you want to get rid of the error messages before then, you will unfortunately have to change your DAX code to not use `NAMEOF`, but instead hardcode the names as strings. If you do this, I recommend adding a comment to the code, so you can easily find the locations where you made the change, once the next version of TE3 comes out.

**Comment by luukhendrikscordstrap** [comment] 2023-06-27 08:04
Hi Daniel,

Im just glad I decided to reach out to get this fixed. Your fast response and quick fix are very much appreciated. I'll leave the code alone for now and wait with suspense for the update.

**Comment by DBojsen** [comment] 2023-07-24 07:42
Hi @luukhendrikscordstrap 

This is now solved in verison 3.9.0.
Thank you for reporting it.

BR David - TE3 support

**Closed by DBojsen** 2023-07-24 07:42 UTC
Labels: bug, backlog
