### ISSUE TITLE
Crash when closing search results tab

### ISSUE THREAD

**Issue by lukiz84** [TabularEditor/TabularEditor3#611] opened 2022-07-25 06:57 UTC
Hi,

- Version 3.3.3.

When i perform a search in the entire model and afterwards close the search result tab, TabularEditor crashes without any error message. It just disappers.

BR
Lukas

**Comment by otykier** [comment] 2022-07-25 07:05
Thanks for reporting. Unfortunately, we're not able to reproduce this issue. Could you share a short recording to showcase the issue? Also, if you check the Event Viewer under Windows Logs > Applications, do you see any .NET Runtime errors around the time of the crash (similar to the screenshot below)?

![image](https://user-images.githubusercontent.com/8976200/180717865-265bbe7c-0d3a-4873-ba29-27b10dd46cce.png)

**Comment by lukiz84** [comment] 2022-07-25 07:08
I'm not able to make a short video due to security restrictions in our Company... but it produced a stacktrace in the events section:

Application: TabularEditor3.exe
CoreCLR Version: 6.0.722.32202
.NET Version: 6.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at TabularEditor.UI.Views.BaseUIViewHelper.GetView(DockPanel panel)
   at TabularEditor.UI.Utils.UILinker.Invalidate()
   at TabularEditor.UI.App.<Invalidate>b__93_0()
   at TabularEditor.UI.App.UiInvokeAsync(Action action)
   at TabularEditor.UI.App.Invalidate()
   at System.Windows.Forms.Application.ThreadContext.Interop.Mso.IMsoComponent.FDoIdle(msoidlef grfidlef)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at TabularEditor.Program.Main()

**Comment by otykier** [comment] 2022-07-25 07:09
Thanks - this is very helpful for our investigation.

**Comment by otykier** [comment] 2022-08-10 11:48
This is fixed in [3.3.4](https://docs.tabulareditor.com/te3/other/release-notes/3_3_4.html), thanks for reporting!

**Closed by otykier** 2022-08-10 11:48 UTC
Labels: bug
