### ISSUE TITLE
Enhancement request: "Start Tabular Editor now" checkbox on installation finished dialog...

### ISSUE THREAD

**Issue by seedjay1** [TabularEditor/TabularEditor3#242] opened 2021-10-03 15:51 UTC
Fast cadence on releases is wonderful, but many installs are sourced from "there's a new version go here to dl it".

We just want to use the program - please put "start TE now" checkbox on ending install dialog (defaulted to yes), so upgraders can get on with their business without extra clicks? :)

**Comment by otykier** [comment] 2021-10-04 06:32
Duplicate of #202

**Closed by otykier** 2021-10-04 06:32 UTC
