### ISSUE TITLE
CTRL+ALT+S does not sync the model

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#762] opened 2022-12-16 21:03 UTC
Hello, 

After creating some measures I get the yellow banner 
![imatge](https://user-images.githubusercontent.com/40455069/208188422-52ed1f4f-44b0-47cc-9d10-d32cca089075.png)
however the keyboard combination does nothing on my end. I need to click on the save model button which is only visible when I'm in the expression editor tab

regards

**Comment by otykier** [comment] 2022-12-19 19:46
That's a bug. The intention was for CTRL+ALT+S to be available at all times. The button being hidden is by design, though, since the regular save button (CTRL+S) will save the model when you are on the expression editor tab (or more precisely, whenever you are **not** on a document tab, such as a DAX Script, DAX Query, Diagram or C# Script).

**Comment by otykier** [comment] 2022-12-23 14:12
This is now fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Moreover, you can now customize the key bindings, so if you prefer to use CTRL+S to always save the current model - that's now possible (**Tools > Preferences > Keyboard**).

**Closed by otykier** 2022-12-23 14:12 UTC
Labels: bug
