### ISSUE TITLE
DAX Query - Option to re-connect

### ISSUE THREAD

**Issue by ram-svkr** [TabularEditor/TabularEditor3#803] opened 2023-01-26 13:02 UTC
When working with DAX queries, after some time (doing something else and then comes back) the connection gets disconnected / timed out, resulting in the error message "..session ID cannot be found..".

Currently I don't see an option to re-connect, so my solution is to always copy-paste over to a new query tab.

It would be nice if Tabular Editor would just re-connect automatically, or if there is a button or shortcut to do it.

![TE3 DAX query connection timeout](https://user-images.githubusercontent.com/117066959/214842073-d43787ec-4cd4-4a65-b6b0-a0da6567e211.png)

**Comment by mlonsk** [comment] 2023-01-26 13:16
Hi @ram-svkr 

Yes this is an open issue, see #650 
We will make sure TE3 can handle this in the future.

**Comment by mlonsk** [comment] 2023-01-26 13:17
Closing as duplicate of #650

**Closed by mlonsk** 2023-01-26 13:17 UTC
Labels: duplicate
