### ISSUE TITLE
Measure doesn't longer show error icon

### ISSUE THREAD

**Issue by bogomda** [TabularEditor/TabularEditor3#14] opened 2021-06-01 04:21 UTC
Measure doesn't longer show error icon
![image](https://user-images.githubusercontent.com/66798479/120266127-4170c500-c26f-11eb-9c35-c1d5e0f85b57.png)

![image](https://user-images.githubusercontent.com/66798479/120266004-0f5f6300-c26f-11eb-95c1-fe6ed50c60c8.png)

**Comment by otykier** [comment] 2021-06-01 05:57
I'm not able to reproduce this on any of my models.

Could you please:

- Provide a detailed step by step on how you triggered this bug
- If possible, save the model as a .bim file inside Tabular Editor and mail the .bim file to: daniel@tabulareditor.com

Thank you!

**Comment by avatorl** [comment] 2021-06-02 10:31
I have this problem as well. When I open a model in TE2 I see yellow error icons on the measures with errors. When I open the same model in TE3 there are no red dots. Then I click Ctrl+S and read dots appears, but only on some broken measures while other broken measures still have no red dots. When I create a new measure with semantic error in this model there is no red dot even after Ctrl+S. When I create a new simple model in Power BI (using 'sample data') and create any measure with a error than I can't reproduce the problem, red dot appears if there is an error in a measure.

![TabularEditor3_2021-06-02_12-23-31 1](https://user-images.githubusercontent.com/59934292/120464606-68c5b000-c39d-11eb-94b8-c49579d9e026.png)

**Comment by otykier** [comment] 2021-06-03 07:19
Should be fixed with [3.0.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.2). Please feel free to reopen this if you experience this issue again.

**Closed by otykier** 2021-06-03 07:19 UTC
Labels: bug
