### ISSUE TITLE
Code Actions Split Multi-column Deletes Instead of splits. 

### ISSUE THREAD

**Issue by eperks-Flynnrg** [TabularEditor/TabularEditor3#1400] opened 2024-11-22 21:32 UTC
### Description

Using the code actions "Split multi-column filter into multiple filters" deletes filters in this certain case.

Code used.

CALCULATE (
    DISTINCTCOUNT ( 'Table'[Key] ),
    'Table'[Type]
        IN { "Red", "Blue" }
            && 'Table'[Field1] = FALSE ()
            && 'Table'[field2] = FALSE ()
)

M Query for example table.
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjQyVtJRCkpNAZIhRaWpQMotMac4VSk2FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Key = _t, Type = _t, Field1 = _t, field2 = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"field2", type logical}, {"Field1", type logical}})
in
    #"Changed Type"

### Tabular Editor 3 Version

3.18

### Screenshots

![Capture3](https://github.com/user-attachments/assets/65a20b61-8ccd-47c7-bb03-abaf942b8c81)
![capture2](https://github.com/user-attachments/assets/021ee696-ad74-47f2-b24d-4097dd5de825)
![Capture1](https://github.com/user-attachments/assets/5e6295f7-4698-4830-afdd-1d1541832480)

### Steps to Reproduce

Clicked on 'Table'[Type] row to use code action.

### Expected behavior

This should split the filters instead of delete

### Windows Version

Windows 10 Enterprise

**Comment by mlonsk** [comment] 2024-11-27 08:25
Hi @eperks-Flynnrg 

I have reproduced the behavior, and there indeed seems to be a bug here. 

We will look into getting it fixed. Thank you for reporting it.

**Comment by otykier** [comment] 2024-12-19 12:26
This issue has been fixed in [3.19.0](https://docs.tabulareditor.com/te3/other/release-notes/3_19_0.html?tabs=downloads). Thanks again for reporting it!

**Closed as completed by otykier** 2024-12-19 12:26 UTC
Labels: issue: bug
