### ISSUE TITLE
mousewheel side scrolling is reversed

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#740] opened 2022-11-30 19:35 UTC
TE3: MouseWheel side-scrolling is the opposite direction than normal ("normal" being SSMS and Excel). Could it be changed?

**Comment by otykier** [comment] 2022-12-23 12:02
Could you provide some more details on this issue? Is it in text editor views, in the TOM Explorer, or some place else? Thanks!

**Comment by zenzeinet** [comment] 2022-12-23 17:09
Pretty much everywhere - In TOM Exporer , DAX Query results, Table preview data, Vertipaq Analyzer... probably elsewhere too.
It is the opposite of most MS Products (i.e. Excel, SSMS and also PowerBI Desktop!)

Not in Pivot Grid... because Pivot Grid cannot be scrolled left-to-right (although it should - maybe this is a different issue)

Thanks!

**Comment by otykier** [comment] 2022-12-29 13:24
Duplicate of #703

**Closed by otykier** 2022-12-29 13:24 UTC
Labels: awaiting reply
