### ISSUE TITLE
Find and Replace not working

### ISSUE THREAD

**Issue by MattAlington** [TabularEditor/TabularEditor3#542] opened 2022-05-18 02:05 UTC
I am trying to use Find and Replace with version 3.2.3

1. I open either DAX or C# script containing code
2. click Ctrl H or Ctrl F (or edit menu, either option).
3. nothing happens.

Expected result - pop up dialog allowing me to search and replace text.

**Comment by MattAlington** [comment] 2022-05-18 02:19
Darren Gosbell suggested I reset to the default layout.  I did this, and now it works.  But why wasn't it visible?  It was definitely not docked anywhere else on the screen as I checked.

**Comment by otykier** [comment] 2022-05-18 04:05
Duplicate of #454

**Closed by otykier** 2022-05-18 04:05 UTC

**Comment by edhans** [comment] 2022-05-20 22:30
Matt, I had this same issue today. My Layouts.json showed the find/replace top/left positions were 4229 and 6852 respectively. If those are pixel coordinates, that was about 3 feet below and 5 feet to the right of my screen, as it is only 1920x1080. Deleting the JSON and restarting TE, then slightly moving the FIND dialog showed it was at 417x1036, which is on screen, so somehow it is getting these super large values pushing it way off screen.
