### ISSUE TITLE
Cannot update format of multiple measures

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#618] opened 2022-08-02 23:25 UTC
This seems new. I am certain I was doing this before. Changing the format when 2+ measures are selected does nothing.

![BulkSelectFormat](https://user-images.githubusercontent.com/45298358/182493225-b803f310-b2b3-4801-9355-0b8eecb0b62a.gif)

**Comment by otykier** [comment] 2022-08-03 03:46
Duplicate of #614

**Closed by otykier** 2022-08-03 03:46 UTC
