### ISSUE TITLE
Get an error in grid when we add a hidden measure

### ISSUE THREAD

**Issue by rvgfox** [TabularEditor/TabularEditor3#1220] opened 2024-01-20 10:56 UTC
### Description

If the measure its hidden, the grid show an error. In PBI it's not happend

### Tabular Editor 3 Version

3.13.10

**Comment by mlonsk** [comment] 2024-01-22 08:01
Hi @rvgfox 

The Pivot Grid is an external component that we use, and unfortunately it does not support displaying hidden fields. 

The workaround is either to unhide the column or use DAX Queries instead. 

Closing as a duplicate of #345

**Closed as completed by mlonsk** 2024-01-22 08:01 UTC
Labels: issue: duplicate
