### ISSUE TITLE
DaxFormatter C# Script not making changes

### ISSUE THREAD

**Issue by nathangiusti** [TabularEditor/TabularEditor3#316] opened 2021-12-02 18:08 UTC
I have tried to run this various ways but all of them have no effect on the model (0 changes). But if I go to the measure expression and right click format dax it makes changes. 

I have tried all of the following, they seem to execute successfully but again 0 model changes and there is definitely dax that needs to be formatted. 

Running 3.1.6

```
foreach( var m in Model.AllMeasures) {
    m.FormatDax();
}
CallDaxFormatter(true);
```

```
FormatDax(Model.AllMeasures);
CallDaxFormatter(true);
```

```
Model.AllMeasures.FormatDax();
CallDaxFormatter(true);
```

Any guidance on what I may be doing wrong.

**Comment by otykier** [comment] 2021-12-02 18:26
Duplicate of #307

**Closed by otykier** 2021-12-02 18:26 UTC
