### ISSUE TITLE
Formatting DAX via script no longer working?

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#592] opened 2022-07-01 21:03 UTC
Is anyone having issues formatting their DAX with the following script?

FormatDax(Model.AllMeasures, true);

It does nothing. Has worked fine for years. Manually formatting via the DAX Formatter icon works fine.

TE 3.3.2

**Comment by otykier** [comment] 2022-07-08 05:32
@edhans are you seeing this issue on all models or only specific ones? Does it work if you format a smaller number of measures, i.e.:

```csharp
FormatDax(Selected.Measures, true);
```

**Comment by edhans** [comment] 2022-07-08 15:15
All models. I just tried a much smaller one with a a few dozen measures and same thing:

- Clicking the Format Dax button works fine when a measure is selected
- using the above script fails in TE/3 - it just does nothing, but works fine in TE/2
- Using the Model.AllMeasures fails in TE/3, but works fine in TE/2

I tried with a "Large model" in the service, a regular model in the service, and a local PBIX connection. Same thing. TE/2 is fine, TE/3 no longer works. This started with the 3.3 series, but I do not recall if it was 3.3.2 or 3.3.0. I never had 3.3.1 installed.

**Comment by otykier** [comment] 2022-07-08 15:23
Thanks. We’ve identified the issue. It’ll be fixed in the next update.

**Comment by otykier** [comment] 2022-07-16 23:50
Fixed in [3.3.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.3).

**Closed by otykier** 2022-07-16 23:50 UTC
Labels: bug

**Comment by rvgfox** [comment] 2023-11-09 13:03
Hi @otykier I'm using:

`FormatDax(Model.AllMeasures, true);`

In TE3 ver 3.11.0 it works but not in a script via command line in TE2 ver 2.20.2

**Comment by otykier** [comment] 2023-11-09 13:23
@rvgfox I'm unfortunately not able to reproduce this. This is the output I get when running it in TE2 CLI:

<img width="931" alt="image" src="https://github.com/TabularEditor/TabularEditor3/assets/8976200/407f857b-9425-4100-8fd3-6e618b2dad41">

What error message are you getting?

**Comment by rvgfox** [comment] 2023-11-09 15:36
No errors, simply doesn't works, the rest of the script works correctly.

**Comment by otykier** [comment] 2023-11-09 18:58
@rvgfox what is the full command you’re using? Also, could you share the full script?
