### ISSUE TITLE
Pivot Grid: drag-and-drop from TOM Explorer does not seem to work

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#776] opened 2022-12-22 20:16 UTC
Pivot Grid: drag-and-drop from TOM Explorer columns does not seem to work

**Comment by otykier** [comment] 2022-12-22 20:35
Are they hidden columns? If so, this is a duplicate of #345

**Comment by zenzeinet** [comment] 2022-12-23 09:32
No, they were normal columns. Strange, I cannot reproduce it now after closing&reopening TE3, and seems to work OK. Maybe my open instance had degraded to specific unusual state. Will get back if it happens again.

What I'm missing is to be able to see the distinct values of a column unless there is a measure also in place - so I cannot use Pivot Grid to quickly see a column values. Is this solvable? (maybe default to a nonblank measure = 1 when nothing is put in the measures area?

**Comment by otykier** [comment] 2022-12-23 09:48
This is also a limitation of the 3rd party pivot grid component we're using.

I recommend adding a blank measure to the model, which you can use in this case. With a pivot grid open, you can then enable the "Show empty values on rows" option, to get something like this:

![image](https://user-images.githubusercontent.com/8976200/209312530-d1f763b6-fa86-437d-a831-1755f5aad00c.png)

Alternatively, you can use a script to output the unique values of a column, and then save that script as a macro. For example such as [this script](https://github.com/PowerBI-tips/TabularEditor-Scripts/blob/main/Basic/Preview%20Distinct%20Values%20of%20Selected%20Columns.csx):
![image](https://user-images.githubusercontent.com/6196804/205235467-7791aabe-963f-4b20-a4ff-3e6761b1fd75.gif)

**Comment by zenzeinet** [comment] 2022-12-23 18:22
Wizardy! Such a good idea for a macro - thanks for pointing it out! Just implemented it (with a top 100 limit to avoid nasty surprises, and changed <distinct> to <values> not to hide the blank row) and works flawlessly!

Now I'm curious - what is the content of your other Macro folders? Just github it if you havent already! (I've seen a few of your macros before - I used the equivalent of batch rename a lot in TE2 until you implemented it natively in TE3) :)

**Comment by otykier** [comment] 2022-12-23 19:05
Oh, these scripts are not mine. You should head over to that GitHub repo and thank the authors there :-)

**Closed** 2023-02-27 09:42 UTC
Labels: awaiting reply
