### ISSUE TITLE
Refresh not possible on calculated-tables-only model

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#828] opened 2023-02-21 14:43 UTC
Minor issue, but models that consist only of calculated tables cannot be Refreshed by TE3 - the refresh menu appears grayed-out

**Comment by mlonsk** [comment] 2023-02-21 15:53
Hi @zenzeinet 
I am not able to reproduce this issue. Quickly created a model only with calculated tables and refresh worked for me both on a SSAS 2022 and Power BI service:
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/11939114/220394346-8ea0069b-a260-404d-804c-8a22627e966a.png">

**Comment by DBojsen** [comment] 2023-03-31 07:32
Hi @zenzeinet 

Since we have not received a reply, I'll go ahead and close this issue.
Please reach out if you still have issues.

BR David - TE3 Support

**Closed by DBojsen** 2023-03-31 07:32 UTC
Labels: needs reproducible example
