### ISSUE TITLE
Error running a DMV

### ISSUE THREAD

**Issue by pawarbi** [TabularEditor/TabularEditor3#822] opened 2023-02-15 14:11 UTC
I am querying below DMV. In TE3  (v3.2.8132) I get an error message. Works fine in TE2, returns the output table.
`ExecuteDax("SELECT * FROM $SYSTEM.TMSCHEMA_TABLES").Tables[0].Output();`

Error: 
![image](https://user-images.githubusercontent.com/62612119/219050534-17f3530f-72e1-4610-a57d-1dda73e512b8.png)

**Comment by mlonsk** [comment] 2023-02-20 15:40
Hi @pawarbi 
I am afraid I cannot reproduce this. 
Running your code in TE3 3.4.2 provides me with the correct output:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/11939114/220149138-86733728-5454-4652-9202-af89e9b46ce9.png">

Which version of TE3 are you using?

**Comment by pawarbi** [comment] 2023-02-21 15:52
@mlonsk You can close. Upgrading to the latest version resolved the issue.

**Comment by mlonsk** [comment] 2023-02-21 16:36
Great, will close it then

**Closed** 2023-02-21 16:37 UTC
Labels: needs reproducible example
