### ISSUE TITLE
Incorrect Port for Power BI File Being Detected

### ISSUE THREAD

**Issue by kczernuszewicz** [TabularEditor/TabularEditor3#882] opened 2023-04-19 12:22 UTC
**Describe the issue**
When trying to connect to Power BI file occasional an error saying "A connection cannot be made. Ensure that the server is running." is being thrown. After cross-checking with Tabular Editor 2 it turned out that Tabular Editor 3 shows wrong port of Power BI file.

**Which version are you currently using?**
Tabular Editor 3, version: 3.5.1.1425
Tabular Editor 3 edition: Desktop

**To Reproduce**
Steps to reproduce the behaviour:
1. Open App
2. Click on File -> Open -> Model from DB
3. Select file you want to connect under Power BI Instance to and click OK
4. Occasionally an error will be thrown

**Expected behaviour**
Correct port number should be detected and a connection should be made.

**Screenshots**
![2023-04-19_14h09_03](https://user-images.githubusercontent.com/63743929/233073139-4be156b8-876e-4a93-8340-6cafc85cea79.png)
![2023-04-19_14h08_51](https://user-images.githubusercontent.com/63743929/233073154-26648a6f-922b-4d42-9da0-437c70485e47.png)
![2023-04-14_16h27_20](https://user-images.githubusercontent.com/63743929/233073178-ec26325b-0188-41aa-aba0-a8b7ee926a33.png)

**Desktop (please complete the following information):**
 - Windows version: 10, 22H2

**Comment by DBojsen** [comment] 2023-04-20 09:17
Hi @kczernuszewicz 

I'm unable to reproduce.  Can I ask you to perform a task next time you see this.

- Open Resource Monitor 
- Go to Network tab
- Expand listening ports
- Send screenshots of all the lines referencing the port numbers (both correct and false)
![image](https://user-images.githubusercontent.com/22237520/233319905-b9eca026-eb65-41f7-951e-6218dc6cbb1b.png)

If you do not want to share it here, please send to support @ tabulareditor.com with a reference to this issue.

BR David - TE3 Support

**Comment by kczernuszewicz** [comment] 2023-04-20 09:45
Hi @DBojsen,

As mentioned in the email, the wrong port does not appear in Listening Ports, it appeared in TCP Connections tho. More details and screenshots sent via email.

**Comment by DBojsen** [comment] 2023-04-24 17:03
Hi @kczernuszewicz 

We have submitted a fix for this issue, which hopefully will solve your issue.
It needs to go thru internal testing before we can release it, but expect it quite soon as a bugfix release.

BR David - TE3 Support

**Comment by otykier** [comment] 2023-05-22 07:29
Hi all.

This was fixed in our [latest release](https://docs.tabulareditor.com/te3/other/release-notes/3_7_1.html?tabs=downloads).

**Closed by otykier** 2023-05-22 07:29 UTC
Labels: bug
