### ISSUE TITLE
Layout isn't remembering where I docked a window 

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#939] opened 2023-07-05 17:38 UTC
**Describe the issue**
I created a layout called "Vertipaq Analyzer Focus" that has the VPA in the main window, as shown:
![image](https://github.com/TabularEditor/TabularEditor3/assets/45298358/20b62c33-08d0-46b8-bc30-67735dcd0c55)

I saved that layout as "Vertipaq Analyzer Focus" but when I select that layout, it moves it back to the bottom where it is by default. Does the layout feature not remember which window a tab is supposed to be in, or am I misunderstanding something?

** Which version are you currently using? **
Tabular Editor 3, version: 3.8
Tabular Editor 3 edition: Enterprise

**To Reproduce**
Desktop and Power BI Service

1. Move Vertipaq Analyzer tab to the main window
2. Save it as a new layout
3. Select that new layout
4. The VPA moves back to its default window, not the one I placed it in.

Windows 10

**Comment by otykier** [comment] 2023-07-06 06:58
Duplicate of #711

**Closed by otykier** 2023-07-06 06:58 UTC
