### ISSUE TITLE
New Import Tables Select all columns crashes TE3

### ISSUE THREAD

**Issue by mlonsk** [TabularEditor/TabularEditor3#204] opened 2021-09-06 11:28 UTC
Hi Daniel

When using the new Import Tables wizard using Select all Columns crashes TE3.

![image](https://user-images.githubusercontent.com/11939114/132210164-9acf78d7-84b9-4933-b72c-86b0d1c725c9.png)

with the following error message:

![image](https://user-images.githubusercontent.com/11939114/132210225-8451dd4c-59eb-4bba-a99d-1ebb2d3ec39f.png)

**Steps to reproduce:**

Right click on model -> Select "Import Tables"
Select "Import tables from existing source" 
Choose Next ... Next..
And "Select all Columns"

Data Source is Azure SQL database using Provider: System.Data.SqlClient

**Comment by helgews** [comment] 2021-09-06 11:33
Was able to reproduce. Error appears when you select "Select all Columns", without having selected any table.
Do you have the same error if you select a table first?

**Comment by otykier** [comment] 2021-09-06 12:04
Thanks for reporting. The issue is that "Select all columns" should be disabled while no table is selected.

**Comment by mlonsk** [comment] 2021-09-06 13:25
Agree that "Select all columns" should be disabled, but it also happens when a table is ticked (1) and then ´ "Select all columns" (2) is selected:
![image](https://user-images.githubusercontent.com/11939114/132224128-c38c4081-7524-49b6-95f5-16c75c951196.png)

It works fine and as expected when selecting the table name:
![image](https://user-images.githubusercontent.com/11939114/132223935-cefc3924-b978-4387-87c2-b37f9aac4350.png)

**Comment by elgerre** [comment] 2021-09-16 11:48
Hey, 

I think I'm facing a similar issue, but one step before the "Select all columns". (Maybe there is something else going on here, I'm not sure)
When I'm trying to import a new table from a Structure Oracle data source I immediately get the same Error message as shown above.
 
<img width="429" alt="oracle_table_import1" src="https://user-images.githubusercontent.com/77665657/133584859-0c22d944-c41d-4cc5-a2d3-612a25915acc.PNG">
<img width="597" alt="oracle_table_import2" src="https://user-images.githubusercontent.com/77665657/133584876-4a3f6054-facd-49c4-8a93-60e37f6e11cc.PNG">

If I then ignore the error message and try to continue with a selection(or SQL Query, I tried both) I get an "Unsupported Data Source" error:
<img width="595" alt="oracle_table_import3" src="https://user-images.githubusercontent.com/77665657/133585116-2d37cf9e-bcf4-4ca8-8c39-50b3b1f25e75.PNG">

Additionally the "Update table schema" seems to also not work anymore for this datasource after switching from TE 3.0.7 to 3.1.0 , says something about an unknown identifier
<img width="470" alt="oracle_table_schema_update" src="https://user-images.githubusercontent.com/77665657/133602672-b6b56c75-fb84-4856-a5c9-50069c5ee17d.PNG">
So I'm thinking about downgrading back to 3.0.7 for the time being, or is there something I missed to fix this?

**Comment by otykier** [comment] 2021-09-16 13:29
@elgerre while we investigate this issue, consider enabling this option (Tools > Preferences > Schema Compare > Use Analysis Services for change detection). This doens't solve the problem with the Import Table Wizard, but at least the "Update table schema" feature should work like it did prior to 3.1.0.

![image](https://user-images.githubusercontent.com/8976200/133620823-d66904b3-ea5f-4b42-997b-06993d92c780.png)

**Comment by otykier** [comment] 2021-09-28 19:17
The "Select all columns" issue has been fixed in [3.1.1](https://docs.tabulareditor.com/te3/other/release-notes/3_1_1.html).

**Closed by otykier** 2021-09-28 19:18 UTC
Labels: bug
