### ISSUE TITLE
Veritpaq Analysisr doesn't work on models with Field Parameters

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#623] opened 2022-08-09 23:27 UTC
When I run the Vertipaq Analysis on a model with a field parameter it fails with the below error and returns no results at all.

At first I thought it was because I created the FP using your script you created a few weeks ago, but I tried it on a model where it was created using the Power BI Desktop tools and the failure was the same. The "Fiscal Group"  field shown below is the Parameter field name created by the user, not the other two fields the FP feature creates.

Note: Dax Studio 2.x works fine on the same models, so it is something in how TE/3 is gathering the info.

![VertipaqError](https://user-images.githubusercontent.com/45298358/183778726-3a67070d-613e-4bc0-9e72-7471c419f75f.png)

**Comment by otykier** [comment] 2022-08-10 02:14
Duplicate of #547 (see that post for a workaround)

**Closed by otykier** 2022-08-10 02:14 UTC
