### ISSUE TITLE
Copy/paste measure breaks TE3

### ISSUE THREAD

**Issue by janizz** [TabularEditor/TabularEditor3#477] opened 2022-03-23 08:31 UTC
This is getting pretty annoying - so when copy pasting a measure (to make a copy) breaks down TE3 with no error or message. When I just fire up TE3 it works, but after some time it just breaks it (TE3 closes).

I have Windows 11, TE3 3.2.2 ver

This is the current example of what paste has in hand:
{
  "InstanceID": "75a4d47c-767b-466d-bf04-b24730d5db16",
  "measures": [
    {
  "name": "# clicks",
  "description": "SUM('Sessions_cube'[impsclick])",
  "expression": "SUM('Sessions_cube'[impsclick])",
  "formatString": "#,0",
  "lineageTag": "4718f6be-9ca8-46ec-9fef-86d69b8d34c9",
  "dataType": "variant",
  "modifiedTime": "2022-03-17T11:53:30.833333",
  "structureModifiedTime": "2022-03-15T13:07:25.146667",
  "annotations": [
    {
      "name": "Format",
      "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />",
      "modifiedTime": "2022-03-17T11:53:30.833333"
    },
    {
      "name": "PBI_ChangedProperties",
      "value": "[\"FormatString\"]",
      "modifiedTime": "2022-03-17T11:53:30.833333"
    }
  ]
}
  ]
}

**Comment by otykier** [comment] 2022-03-23 09:02
Hi @janizz 
Thanks for reporting. Could you take a look in the Windows Event Viewer, and look for any .NET Runtime errors around the time of the crash in the Application Logs. Please share the event details here. Thanks!

**Comment by janizz** [comment] 2022-03-23 10:10
Yep, exactly that.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/2431369/159675232-1965e170-9a28-4417-9b7d-392a3faa37cb.png">

Application: TabularEditor3.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at Microsoft.AnalysisServices.Tabular.NamedMetadataObjectCollection`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ValidateCanAdd(System.__Canon)
   at Microsoft.AnalysisServices.Tabular.MetadataObjectCollection`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon)
   at TabularEditor.TOMWrapper.TabularObjectCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InternalAdd(System.__Canon)
   at TabularEditor.TOMWrapper.ColumnCollection.InternalAdd(TabularEditor.TOMWrapper.Column)
   at TabularEditor.TOMWrapper.CalculatedTableColumn.CreateNew(TabularEditor.TOMWrapper.Table, System.String)
   at TabularEditor.TOMWrapper.CalculatedTable.AddCalculatedTableColumn(System.String, System.String, System.String, TabularEditor.TOMWrapper.DataType)
   at TabularEditor.TOMWrapper.TabularModelHandler+<>c__DisplayClass84_0.<SemanticAnalyzer_CalculatedTableChange>b__0()
   at TabularEditor.TOMWrapper.TabularModelHandler.SemanticAnalysisChange(System.Action)
   at TabularEditor.TOMWrapper.TabularModelHandler.SemanticAnalyzer_CalculatedTableChange(System.Object, Dax.Analyzer.CalculatedTableChangeEventArgs)
   at Dax.Analyzer.Ast.AstHelper.AnalyzeCalculatedTable(Microsoft.AnalysisServices.Tabular.CalculatedPartitionSource, Dax.Analyzer.IDependencyResolver, Dax.Analyzer.AnalyzerSettings, System.EventHandler`1<Dax.Analyzer.CalculatedTableChangeEventArgs>)
   at Dax.Analyzer.SemanticAnalyzer.Analyze(Dax.Analyzer.ReferencingObject, Boolean, Boolean, Dax.Analyzer.EvaluationContext)
   at Dax.Analyzer.SemanticAnalyzer.FullSemanticAnalysisInternal(Boolean, Boolean)
   at Dax.Analyzer.SemanticAnalyzer.FullSemanticAnalysisWithEvents(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

**Comment by otykier** [comment] 2022-03-23 10:36
Thanks, that’s very helpful! We’ll look into it.

**Comment by janizz** [comment] 2022-03-24 09:03
Seemingly this happens only on 1 of my data models that is in a workspace that is set to 'Large dataset storage format'. The other ones are not. Hope this helps.

**Comment by otykier** [comment] 2022-04-04 10:03
@janizz would it be possible for you to share a .bim file of the model where this issue arises? If so, please send it to daniel@tabulareditor.com - thanks!

**Comment by janizz** [comment] 2022-04-13 15:45
@otykier  how can I do that in an easy way with TE?

**Comment by otykier** [comment] 2022-04-13 16:41
Or a .pbit (Power BI Template) file that you export through Power BI Desktop, that would also be fine.

**Comment by janizz** [comment] 2022-04-14 07:59
I renamed .zip as github wouldn't allow .pbit files.

[CE_main.pbit.zip](https://github.com/TabularEditor/TabularEditor3/files/8487348/CE_main.pbit.zip)

**Comment by janizz** [comment] 2022-05-18 12:51
Any development on this one? My TE3 still is still breaking ... scared of copy/pasting measures on this model :/

**Comment by otykier** [comment] 2022-05-18 12:55
Hi @janizz 
Yes, we believe we have identified the root cause. The next update of TE3 (ETA end of month) will contain the fix.

**Comment by otykier** [comment] 2022-06-28 14:05
Hi @janizz 
Have you encountered this issue after upgrading to [3.3.0](https://github.com/TabularEditor/TabularEditor3/releases/latest) or higher?

**Comment by mlonsk** [comment] 2023-01-16 11:12
Closing this has it seems to have been solved, please reopen if this is not the case

**Closed by mlonsk** 2023-01-16 11:12 UTC
Labels: bug, awaiting reply
