### ISSUE TITLE
Duplicate isn't the same as Copy|Paste - seems counter intuitive

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#1379] opened 2024-10-04 16:13 UTC
### Description

In a model in the service, I used the right-click "Duplicate" item to duplicate a field parameter. It copied the DAX, but not much else. The meta data describing which fields were hidden, sort by properties, and the extended properties for the special Field Parameter sauce were missing. I thought that is just the way it worked.

Co-worker said he never had that issue, and turns out, he uses the Copy|Paste feature. That copies 100% of everything.

Now I am apprehensive about using the Duplicate feature on anything not knowing what properties are not being truly copied.

I thought Duplicate was just a single action to do the same as Copy|Paste. Is it supposed to be and this is a bug, or is it not designed to do that, and if not, why? What is the logic in not replicating everything?

### Tabular Editor 3 Version

3.17.0

**Comment by otykier** [comment] 2024-10-09 13:16
Thanks for reporting this, Ed. It seems like we have a bug here, because the intention was definitely for Duplicate to be functionally equivalent to Copy/Paste, but without having to touch the clipboard. We'll investigate.

**Comment by otykier** [comment] 2024-12-11 21:15
Hi Ed,
We've now had a chance to look into this in more details, but unfortunately we're not able to reproduce the issue as you describe. I.e. when we use the "Duplicate" command on a Field parameter table, we see the created copy set up with the exact same metadata (except of course the name of the table itself) as the original table:

![image](https://github.com/user-attachments/assets/2edaa749-7b12-46b9-8782-7ddbf5cb2a32)

New table:

![image](https://github.com/user-attachments/assets/8f1390dd-88c6-4e98-816e-62c680c0e0b3)

Perhaps it was a fluke? Let us know if you are still seeing this issue.

**Comment by otykier** [comment] 2024-12-19 12:25
FWIW, we changed the behavior of copy/paste/duplicate slightly in [3.19.0](https://docs.tabulareditor.com/te3/other/release-notes/3_19_0.html?tabs=downloads), such that when you copy/paste or duplicate a table, all table references (for example through fully qualified column or measure references) within child objects of that table, including RLS expressions, are automatically updated to match the new name of the table.

I'll close this ticket for now, but feel free to reopen if you encounter any issues with this again.

**Closed as completed by otykier** 2024-12-19 12:25 UTC
Labels: issue: bug

**Comment by edhans** [comment] 2024-12-19 17:56
Thanks. I meant to test this earlier this week. with 3.19 though, when I duplicate a field parameter, all of the metadata is copied so it seems to be working.
