### ISSUE TITLE
Can't create Macro Toolbar

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#607] opened 2022-07-17 07:24 UTC
Probably related to other issues, but it's not possible to create a macro toolbar either. 
When I try to select commands from the macro section, nothing appears.  
Also, the dialog box is taller than most resolutions, so you need to reize the dialog to see the ok button -- 

![image](https://user-images.githubusercontent.com/40455069/179388353-2babda3a-d180-4da9-a73d-1055be2120c2.png)

**Comment by otykier** [comment] 2022-07-17 07:26
Is this in 3.3.3?

**Comment by bernatagulloesbrina** [comment] 2022-07-17 07:27
Yes
![image](https://user-images.githubusercontent.com/40455069/179388430-8ccf208a-d05a-43d8-a07a-343848ac52a5.png)

**Comment by otykier** [comment] 2022-07-17 07:31
Ok, I see you created another post with macros now showing in the menu. This issue is related (since your macros are not compiling properly). Only when macro compilation succeeds will macros show up in the context menu as well as in the Customize dialog. 

Leaving this open to track the issue with the size of the dialog box.

**Comment by bernatagulloesbrina** [comment] 2022-07-17 07:41
I tried opening the code of each macro and click to "modify macro" to sort of recompile it and the error seems to come from the "Error" and "SelectTable" functions. But these should be fixed in this release, right? 

![image](https://user-images.githubusercontent.com/40455069/179388878-4f8d88ab-4186-4ca9-8fdb-b680f3796114.png)

**Comment by bernatagulloesbrina** [comment] 2022-07-17 07:43
not all  my macros use these functions, so it seems that if one of your macros does not compile properly then you don't see any of your macros

**Comment by otykier** [comment] 2022-07-25 07:35
Closing this as a duplicate of #606

**Closed by otykier** 2022-07-25 07:35 UTC
