### ISSUE TITLE
[Issue] calculation group screen is very very slowly in TabularEditor2 ！！！！！

### ISSUE THREAD

**Issue by hzykelvin** [TabularEditor/TabularEditor3#946] opened 2023-07-15 05:29 UTC
**Describe the issue**
It is very very slowly in TabularEditor2，even if roll the Scroll bar ！！！！！For example, calculation group screen !
but it is very very fast in TabularEditor3 to do the same operation！
and Chinese characters are displayed abnormally in TabularEditor2 but it is normal in TabularEditor3.
Why？Did you create the difference on purpose, because TabularEditor2 is for free and there is a charge for TabularEditor3????

** Which version are you currently using? **

**To Reproduce**

**Expected behavior**

**Screenshots**

![中文显示](https://github.com/TabularEditor/TabularEditor3/assets/78143982/77dde833-5404-429a-91cd-394371deadaa)
![中文显问题2](https://github.com/TabularEditor/TabularEditor3/assets/78143982/2d8f1905-c31d-4238-8488-552c1abb6c9d)

**Desktop (please complete the following information):**
 - Windows version: [e.g. 10/11]

**Additional context**

**Comment by otykier** [comment] 2023-07-15 05:45
> Why？Did you create the difference on purpose, because TabularEditor2 is for free and there is a charge for TabularEditor3????

I absolutely did not intend for TE2 to be slow. It’s an open source product, which uses open source components that were not created by me. For example, the text editor in TE2 is [this one](https://github.com/PavelTorgashov/FastColoredTextBox), which apparently has issues when rendering Chinese characters. Feel free to submit a pull request to that repository, if you manage to fix this issue.

Closing this ticket, as the issue is not related to TE3.

**Closed by otykier** 2023-07-15 05:45 UTC

**Comment by hzykelvin** [comment] 2023-07-15 06:59
ok, I didn't know it was made by open source components. thx for your contribution！i give my apologize to you
