### ISSUE TITLE
Variables returning scalar values not recognized by Intellisense

### ISSUE THREAD

**Issue by edhans** [TabularEditor/TabularEditor3#615] opened 2022-07-29 21:46 UTC
When I am referencing variables, only variables that return a table show up in Intellisense. Variables that return a scalar value don't show up and I have to manually type them out. Once I do, they show up green, so the editor recognizes they are variables. See animated GIF attached.

This is 3.3.3.

![ScalarValuesNotRecognized](https://user-images.githubusercontent.com/45298358/181847193-a2c9de8d-2028-448b-aeb0-5485e426badd.gif)

**Comment by otykier** [comment] 2022-08-01 09:06
Hi @edhans
We're unfortunately not able to reproduce this issue. Any chance you could send a minimal repro (.pbit or .bim file) to support@tabulareditor.com?

**Comment by edhans** [comment] 2022-08-01 14:45
Yes, I will send the file. It is test data and pretty small. I did forget to mention this was in a Calculation Item in a calg group, not a measure, which might be the diff. In the file I send, to to the LNPL calc item, go after varAverage, and try to reference it and get intellisense to pick it up.

**Comment by otykier** [comment] 2022-08-10 11:48
This is fixed in [3.3.4](https://docs.tabulareditor.com/te3/other/release-notes/3_3_4.html). Thanks for reporting!

**Closed by otykier** 2022-08-10 11:48 UTC
Labels: bug
