### ISSUE TITLE
Can't connect to a PBI desktop model if I launch the application directly (not from the external tools bar)

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#583] opened 2022-06-26 15:37 UTC
If I launch tabular editor 3 from the external tools toolbar all is good
however if I first open tabular editor 3 and then try to connect to the model of my pbid instance, the OK button is not enabled even if I select the file from the dropdown

![image](https://user-images.githubusercontent.com/40455069/175822018-813b5bc6-4ec7-4754-9a86-9b06eb89bc91.png)

**Comment by otykier** [comment] 2022-06-27 06:55
Duplicate of #579

**Closed by otykier** 2022-06-27 06:55 UTC
