### ISSUE TITLE
Nested /* /* */ */ comments not properly parsed

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor3#768] opened 2022-12-21 12:50 UTC
Hi,
In DAX (as per "it works correctly in SSAS") , the following is allowed as the /* */ comments can be nested, but returns a parsing error in TE3:

````
evaluate 
{ 3
/*
/* */
*/
}
````

**Comment by otykier** [comment] 2022-12-21 12:58
Duplicate of #681

**Closed by otykier** 2022-12-21 12:58 UTC

**Comment by zenzeinet** [comment] 2022-12-21 16:27
Oops true!. Didn't find it on a quick scan of the open issues :)
