### ISSUE TITLE
ROLLUPADDISSUBTOTAL isn't recognized as a valid function name

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor3#16] opened 2021-06-01 12:07 UTC
I am trying out the TE3 and it appears that ROLLUPADDISSUBTOTAL isn't getting recognized, also the IntelliSense doesn't allow to select the column that is to be used for grouping.

![image](https://user-images.githubusercontent.com/73054674/120319699-eb4b6280-c2fe-11eb-9532-a0c885853d14.png)

https://user-images.githubusercontent.com/73054674/120320308-a411a180-c2ff-11eb-914c-eaec8fa93b0a.mp4

The result is received but the error is still shown in the Messages and ROLLUPADDISSUBTOTAL is highlighted with red squiggly lines
![image](https://user-images.githubusercontent.com/73054674/120320454-d4f1d680-c2ff-11eb-80b0-ac2d821e0f37.png)

**Comment by otykier** [comment] 2021-06-01 12:53
Thanks for reporting. We'll investigate ASAP!

**Comment by otykier** [comment] 2021-06-07 21:10
Fix coming soon! Also improved autocomplete for ROLLUPADDISSUBTOTAL as can be seen here:

![rollupaddissubtotal](https://user-images.githubusercontent.com/8976200/121088010-6e7c2500-c7e5-11eb-927b-a25dbbfd2293.gif)

**Comment by otykier** [comment] 2021-06-08 00:44
Fixed in [3.0.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.3). Please feel free to open a new ticket if you feel the issue is not resolved.

**Closed by otykier** 2021-06-08 00:44 UTC
Labels: bug
