### ISSUE TITLE
Error "An item with the same key has already been added. Key:Microsoft.AnalysisServices.Tabular.DataColumn" when saving model

### ISSUE THREAD

**Issue by verscev80** [TabularEditor/TabularEditor3#1393] opened 2024-11-06 08:12 UTC
### Description

After saving a model in PowerBI, we receive the issue above. We get this issue every time we try to save. Since nothing has changed to the model, we tried the same action with the previous version ( 3.17 ) and this is working without any issue. 
Once we saved the model within version 3.17, it is possible again to save it under version 3.18 as well. 
Only when we deploy a model under 3.18 and save it afterwards, we get the issue. 

### Tabular Editor 3 Version

3.18

### Screenshots

![2024-11-06_09-05-35](https://github.com/user-attachments/assets/10227bd4-86d2-4611-9855-42c08b757cca)

**Comment by otykier** [comment] 2024-11-06 13:23
Thanks for reporting this. Happy to let you know that we've identified the root cause and will provide an updated build asap where this is fixed. In the mean time, please downgrade to [3.17.1](https://docs.tabulareditor.com/te3/other/release-notes/3_17_1.html?tabs=downloads). I apologize for the inconvenience.

**Comment by otykier** [comment] 2024-11-06 13:24
FYI, this is the same as #1390

**Comment by otykier** [comment] 2024-11-11 12:40
This is now fixed in [3.18.1](https://docs.tabulareditor.com/te3/other/release-notes/3_18_1.html?tabs=downloads). Thanks for reporting it, and for your patience while we worked on a fix.

**Closed as completed by otykier** 2024-11-11 12:40 UTC
Labels: issue: bug
